DROP TABLE IF EXISTS relations;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS phones;
DROP TABLE IF EXISTS acc_pictures;
DROP TABLE IF EXISTS comm_pictures;
DROP TABLE IF EXISTS chat_rooms;
DROP TABLE IF EXISTS communities;
DROP TABLE IF EXISTS accounts;

